AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '*.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'config/initializers/**/*'
    - 'spec/dummy/**/*'
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    # most of the specs file have long line length but readability is still good

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    # most of the specs file have long block length but readability is still good

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false
